
CREATE USER nelio WITH PASSWORD '123456';
CREATE DATABASE push_down_db OWNER nelio;

GRANT ALL PRIVILEGES ON DATABASE push_down_db TO nelio;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO nelio;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO nelio;